task_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls',namespace='tasks'))

]

tasks/urls.py
# tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.task_main, name='task_main'),
    path('all/', views.task_list, name='task_list'),
    path('completed/', views.task_completed, name='task_completed'),
    path('<int:task_id>/', views.task_detail_all, name='task_detail_all'),
    path('completed/<int:task_id>/', views.task_detail, name='task_detail'),
]

tasks/models.py
from django.db import models

class CompletedManager(models.Manager):
    def get_queryset(self):
        return(
            super().get_queryset().filter(is_completed=True)
        )

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    completed = CompletedManager()

    def __str__(self):
        return f"{self.title} - {'Completed' if self.is_completed else 'Pending'}"

tasks/views.py
from django.shortcuts import render ,get_object_or_404
from .models import Task

def task_main(request):
    return render(request, 'tasks/task/main.html')
def task_list(request):
    tasks = Task.objects.all()
    return render(
        request,
        'tasks/task/list.html',
        {'tasks': tasks}
    )
def task_completed(request):
    tasks_completed=Task.completed.all()

    return render(
        request,
        'tasks/task/completed_list.html',
        {'tasks': tasks_completed}
    )


def task_detail(request, task_id):
    # try:
    #     task = Task.objects.get(id=task_id)
    #
    # except Task.DoesNotExist:
    #     raise Http404("Task not found")

    task = get_object_or_404(Task, id=task_id, is_completed=True )

    return render(
        request,
        'tasks/task/detail.html',
        {'task': task}
    )

def task_detail_all(request, task_id):
    # try:
    #     task = Task.objects.get(id=task_id)
    #
    # except Task.DoesNotExist:
    #     raise Http404("Task not found")

    task = get_object_or_404(Task, id=task_id )

    return render(
        request,
        'tasks/task/detail.html',
        {'task': task}
    )

templates/tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Task Management{% endblock %}</title>
    <link href="{% static 'tasks/css/tasks.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    <div id="sidebar">
        <h2>TaskTrackMaster</h2>
        <h3>A Task Flow and Management System</h3>
        <br>
    <p style="text-align: justify;">TaskTrackMaster is designed to empower individuals and teams to streamline their workflows, prioritize tasks, and achieve their goals with ease. 

Whether you’re managing personal projects, collaborating with colleagues, or overseeing complex assignments, our intuitive interface and robust features will help you stay on track and increase efficiency. With powerful tools for task assignment, progress tracking, and deadline management, you’ll have everything you need to turn ideas into action.

Experience the benefits of enhanced collaboration, clear accountability, and improved time management.</p> 
    <p style="text-align: justify;">Say goodbye to scattered to-do lists and overwhelming workloads; welcome to a more organized and productive way of working. Let’s embark on this journey towards achieving excellence together!

Thank you for choosing TaskTrackMaster, where every task counts!</p>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

templates/tasks/task/completed_list.html
<html lang="en">
{% extends "tasks/base.html" %}

{% block title %}Completed Tasks{% endblock %}

{% block content %}
    <h1>Completed Tasks</h1>
    {% for task in tasks %}
        <h2>
            <a href="{% url 'tasks:task_detail' task.id %}">{{ task.title }}</a>
        </h2>
        <p>{{ task.description|truncatewords:20 }}</p>
        <p>Created at: {{ task.created_at }}</p>
        <p>Updated at: {{ task.updated_at }}</p>
    {% empty %}
        <p>No completed tasks available.</p>
    {% endfor %}
    
    <a href="{% url 'tasks:task_main' %}">Back to Main</a>
{% endblock %}

templates/tasks/task/detail.html
<html lang="en">
{% extends "tasks/base.html" %}

{% block title %}{{ task.title }}{% endblock %}

{% block content %}
    <h1>{{ task.title }}</h1>
    <div lang="en" class="task-details">
        <p><strong>Title:</strong> {{ task.title }}</p>
        <p style="text-align: justify;"><strong>Description:</strong> {{ task.description|linebreaks }}</p>
        <p><strong>Status:</strong> <span class="status {% if task.is_completed %}completed{% else %}not_complete{% endif %}">{{ task.is_completed|yesno:"Completed,Pending" }}</span></p>
        <p><strong>Created at:</strong> {{ task.created_at }}</p>
        <p><strong>Updated at:</strong> {{ task.updated_at }}</p>
    </div>
    
    <a href="{% url 'tasks:task_list' %}" class="back-btn">Back to Task List</a>
{% endblock %}

templates/tasks/task/list.html
<html lang="en">
{% extends "tasks/base.html" %}

{% block title %}All Tasks{% endblock %}

{% block content %}
    <h1>All Tasks</h1>
    {% for task in tasks %}
        <div lang="en" class="task-item">
            <p><strong>Title:</strong> {{ task.title }} <a href="{% if task.is_completed %}{% url 'tasks:task_detail' task.id %}{% else %}{% url 'tasks:task_detail_all' task.id %}{% endif %}">(Show)</a></p>
            <p style="text-align: justify;"><strong>Description:</strong> {{ task.description|truncatewords:20 }}</p>
            <p><strong>Status:</strong> <span class="status {% if task.is_completed %}completed{% else %}not_complete{% endif %}">{{ task.is_completed|yesno:"Completed,Pending" }}</span></p>
            <p><strong>Created at:</strong> {{ task.created_at }}</p>
            <p><strong>Updated at:</strong> {{ task.updated_at }}</p>
        </div>
    {% empty %}
        <p>No tasks available.</p>
    {% endfor %}
    
    <a href="{% url 'tasks:task_main' %}" class="back-btn">Back to Main</a>
{% endblock %}

templates/tasks/task/main.html
<html lang="en">
{% extends "tasks/base.html" %}

{% block title %}Task Management{% endblock %}

{% block content %}
    <h1>Task Management System with Django and MySQL</h1>
    <br>
    <ul>
        <li><a href="{% url 'tasks:task_list' %}">Tasks List</a></li>
        <li><a href="{% url 'tasks:task_completed' %}">Completed Tasks List</a></li>
    </ul>
{% endblock %}